### ISSUE TITLE
Rows jump around during drag-and-drop when there are hidden columns

### ISSUE THREAD

**Issue by helen** [10up/simple-page-ordering#11]
Noted on the [WordPress.org forums as a Yoast SEO conflict](https://wordpress.org/support/topic/conflict-with-yoast-seo-plugin-9/), but it appears to be an issue of any hidden columns. I'm guessing something in the drag-and-drop calculates the space needed for those hidden columns and we need to account for that somewhere.

More .org forum posts:
* https://wordpress.org/support/topic/row-height-on-drag-width/
* https://wordpress.org/support/topic/breaks-when-any-screen-option-in-unchecked/

### Screencast
![Demo GIF](https://user-images.githubusercontent.com/906334/37044413-0befe536-2129-11e8-828c-5e65f4872c4a.gif)

**Comment by smerriman** [comment]
I already reported this, along with the fix 2 years ago. Last time the plugin was updated I contacted Jake via Slack and he said he'd look into it. Still hasn't been included.

https://wordpress.org/support/topic/breaks-when-any-screen-option-in-unchecked/

**Comment by helen** [comment]
@smerriman Yup, I went through more forum posts after I first opened this issue and already included a link to yours in the issue! If you’re up for a pull request that’d be great, otherwise I’ll work this into a maintenance cycle now that it’s less of a one-person show :)

**Comment by helen** [comment]
Looks like there was a neglected PR from @benhuson over at https://github.com/jakemgold/simple-page-ordering/pull/7/ - I've asked if he's up for bringing that over to the new file structure and opening a PR on this repo. I'll do a deeper review and follow up within the week - at the very least, I can use the co-authors functionality to get him credit.

**Comment by benhuson** [comment]
Hi Helen,

Looks like I couldn’t follow up your comment in the old repo as it has now been archived.

I may be able to put aside time tomorrow to check my old PR and see how it applies a PR to the latest repo.

Thanks

Ben

**Comment by benhuson** [comment]
@helen I have submitted a fresh PR against this repo. Fix works for me.

https://github.com/10up/simple-page-ordering/pull/15

I've only submitted changes for the src JS file and tested in script debug mode. If all OK, the changes will still need to be applied to the `.min.js` file.

**Comment by adamsilverstein** [comment]
Fixed in https://github.com/10up/simple-page-ordering/pull/15
