### ISSUE TITLE
Add a "Build release zip" GitHub Action

### ISSUE THREAD

**Issue by faisal-alvi** [10up/simple-page-ordering#117]
### Is your enhancement related to a problem? Please describe.

A new Action is released: https://github.com/10up/action-wordpress-plugin-build-zip/. This is already set up in a few PRs: [Insert Special Characters](https://github.com/10up/insert-special-characters/pull/174), [Autoshare for Twitter](https://github.com/10up/autoshare-for-twitter/pull/201) and [Simple Podcasting](https://github.com/10up/simple-podcasting/pull/199). As an example, you can see/download the Simple Podcasting zip [here](https://github.com/10up/simple-podcasting/actions/runs/3596557206).

Please go ahead and create the same in this repository.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
@dkotter if this one is already added in https://github.com/10up/simple-page-ordering/pull/112, please link and close this ticket.

**Comment by iamdharmesh** [comment]
Yes it is already added @faisal-alvi, but we can update it to use  https://github.com/10up/action-wordpress-plugin-build-zip action instead of .sh file. let me do that.
