### ISSUE TITLE
Ignore input elements in the row

### ISSUE THREAD

**Issue by helen** [10up/simple-page-ordering#13]
If there are input/form elements in the row, they cannot be interacted with because of drag and drop. There are plenty of other spaces to "grab" the row, so we should be able to safely ignore those elements. This did not affect quick edit in my testing (despite a forum post linked below about it) but worth checking there as well.

.org forum posts:
* https://wordpress.org/support/topic/exception-for-inputs-suggestion/ (has technical suggestion and workaround)
* https://wordpress.org/support/topic/bugs-with-all-in-one-seo-pack-plugin/
* https://wordpress.org/support/topic/compatibility-w-admin-columns-plugin/
* https://wordpress.org/support/topic/issue-with-quick-edit/

**Comment by NateWr** [comment]
This has caused issues for one of my plugins as well. I've tested @oscarssanchez's PR https://github.com/10up/simple-page-ordering/pull/21 and it fixed the issue for me, without causing any noticeable side effects.

If a different approach to solving this is desired, I'd be happy to work up a PR. :+1:
