### ISSUE TITLE
Embedded git repository

### ISSUE THREAD

**Issue by theamnesic** [10up/simple-page-ordering#169]
### Describe the bug

Hi!

Since the last update, when I `git add .` on my project, this warning appears:  

```

warning: adding embedded git repository: wp-content/plugins/simple-page-ordering/10up-lib/wp-compat-validation-tool
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint: 
hint: 	git submodule add <url> wp-content/plugins/simple-page-ordering/10up-lib/wp-compat-validation-tool
hint: 
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint: 
hint: 	git rm --cached wp-content/plugins/simple-page-ordering/10up-lib/wp-compat-validation-tool
hint: 
hint: See "git help submodule" for more information.

```

### Steps to Reproduce

Install last update and `git add .`.

### Environment information

WordPress 6.3.2
Simple Page Ordering 2.6.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mjot** [comment]
We have the same problem, all our wordpress projects are managed via git, so we now have the error everywhere.

**Comment by jeffpaul** [comment]
@Sidsector9 is this another one related to the wp compat tool?

**Comment by Sidsector9** [comment]
@jeffpaul that's correct. I'll release a new version with the fix today.

**Comment by Sidsector9** [comment]
Version [2.6.1 released](https://github.com/10up/simple-page-ordering/releases/tag/2.6.1) which fixes this issue. Closing as resolved.
