### ISSUE TITLE
PHP Warning - undefined array key class-simple-page-ordering.php 433

### ISSUE THREAD

**Issue by sissibieber** [10up/simple-page-ordering#200]
### Describe the bug

when called in the admin, page overview, I get the following php warning:
Undefined array key 32 in /xxx/plugins/simple-page-ordering/class-simple-page-ordering.php 433

While 32 is the parent, that has 2 child pages, which are both set to draft

### Steps to Reproduce

1. admin area
2. pages overview
3. warning in debug.log

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mjot** [comment]
I can confirm this bug, same behaviour for us.
