### ISSUE TITLE
Offset errors when order custom post types

### ISSUE THREAD

**Issue by tahninial** [10up/simple-page-ordering#204]
### Describe the bug

Since the April release, I seem to have got a bunch of unidentified offset notices triggered by line 433 of class-simple-page-ordering.php

### Steps to Reproduce

I seem to be able to replicate this each and every time I reorder one of the custom post types on this particular website, but ordering the default page post type didn't seem to cause it. I haven't been able to narrow anything else down but am happy to do more tests and provide more info as required.

### WordPress information

Wordpress 6.5.3 and plugin 2.7.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peterwilsoncc** [comment]
Thanks for the report @tahninial.

This bug was reported in #200 and has been fixed in PR #203 which is scheduled to be included in the next version of the plugin.

I'll close this ticket off as unplanned (duplicate) as the fix is currently in the release queue.
