### ISSUE TITLE
Reset ordering

### ISSUE THREAD

**Issue by pattonwebz** [10up/simple-page-ordering#24]
This is a crosspost of an issue reported at the plugin directory support forums: https://wordpress.org/support/topic/reset-to-alphabetical-order/

> We installed the plugin, moved around a couple of pages but ultimately ended up with an almost random order of pages for some reason. This is particularly an issue for the automated user sitemap that we have that currently displays things in an unordered fashion.
>
>How do we reset the order of pages to an alphabetical order permanently? We have too many pages to practically do it manually.

We could add a feature that simply updates each posts order to the same number (to `0` probably?) and let a different default ordering system take over.

**Comment by ruscoe** [comment]
@jeffpaul I'd like to take a look at this one. I'll come up with a PR once I have something.
