### ISSUE TITLE
Allow pages to be moved to be children of other pages

### ISSUE THREAD

**Issue by amityweb** [10up/simple-page-ordering#25]
Doesn't move pages to child?

**Comment by jeffpaul** [comment]
@amityweb apologies for the delayed response, but welcome to Simple Page Ordering!  Can you provide some more details around your question, especially confirming your environment details if you're seeing a bug so we can better triage for you?

**Comment by amityweb** [comment]
Sorry but this was over 1.5 years ago I have no idea I would have obviously found an alternate solution. I am guessing here, but it sounds like your page ordering plugin did not allow me to move the page as a child of a parent page, which Nested Pages can do for example. I dont need help with this anymore, but if this is still not possible then I recommend it as a feature request. Sometimes you dont want to just order a page but move it to a sub-page.
