### ISSUE TITLE
Avoid post__not_in

### ISSUE THREAD

**Issue by nicholasio** [10up/simple-page-ordering#3]
The plugin currently uses post__not_in https://github.com/10up/simple-page-ordering/blob/develop/simple-page-ordering.php#L169.

Ideally we shouldn't be using it, but haven't dig into it to see if its feasible to rewrite that method without `post__not_in`.

https://10up.github.io/Engineering-Best-Practices/php/#performance

Also had this called out by VIP recently.

**Comment by jeffpaul** [comment]
@nicholasio thanks for calling that out, is it something you'd be able to work up a PR to resolve?
