### ISSUE TITLE
Address VIP GO review

### ISSUE THREAD

**Issue by pereirinha** [10up/simple-page-ordering#37]
**Is your enhancement related to a problem? Please describe.**
While adding this plugin to a WordPress VIP GO project, a few problems were flagged.

**Describe the solution you'd like**
Ideally, the next release addresses this feedback.

**Designs**
<img width="623" alt="Screenshot 2020-02-04 at 09 50 30" src="https://user-images.githubusercontent.com/2189187/73733615-3027af00-4734-11ea-8274-1c253233d998.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 50 24" src="https://user-images.githubusercontent.com/2189187/73733616-3027af00-4734-11ea-80d7-7f300da1d857.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 50 15" src="https://user-images.githubusercontent.com/2189187/73733618-30c04580-4734-11ea-8af8-5d23d67aee31.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 49 54" src="https://user-images.githubusercontent.com/2189187/73733619-30c04580-4734-11ea-8cd8-d1d8dacf800d.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 49 39" src="https://user-images.githubusercontent.com/2189187/73733620-30c04580-4734-11ea-9b28-6655600bee27.png">

<img width="623" alt="Screenshot 2020-02-04 at 09 49 01" src="https://user-images.githubusercontent.com/2189187/73733592-2e5deb80-4734-11ea-9259-a2d87290d69e.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 49 16" src="https://user-images.githubusercontent.com/2189187/73733594-2e5deb80-4734-11ea-959d-9ba79ce80b1e.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 51 06" src="https://user-images.githubusercontent.com/2189187/73733595-2e5deb80-4734-11ea-924c-106bfb218079.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 50 58" src="https://user-images.githubusercontent.com/2189187/73733596-2e5deb80-4734-11ea-8c95-153ca24020bf.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 51 21" src="https://user-images.githubusercontent.com/2189187/73733597-2e5deb80-4734-11ea-919d-2c24d0241a42.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 49 27" src="https://user-images.githubusercontent.com/2189187/73733598-2ef68200-4734-11ea-8fb3-ae3d241ad0cb.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 50 48" src="https://user-images.githubusercontent.com/2189187/73733602-2ef68200-4734-11ea-9b44-5a85e02ae744.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 52 47" src="https://user-images.githubusercontent.com/2189187/73733604-2ef68200-4734-11ea-9354-20fc3140229a.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 52 39" src="https://user-images.githubusercontent.com/2189187/73733605-2ef68200-4734-11ea-8a2b-69773af5ce85.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 52 33" src="https://user-images.githubusercontent.com/2189187/73733606-2ef68200-4734-11ea-9ce5-719e3651d0e2.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 52 24" src="https://user-images.githubusercontent.com/2189187/73733607-2f8f1880-4734-11ea-9a31-a58efc75043e.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 52 15" src="https://user-images.githubusercontent.com/2189187/73733608-2f8f1880-4734-11ea-90cb-b7ef1528a704.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 52 02" src="https://user-images.githubusercontent.com/2189187/73733609-2f8f1880-4734-11ea-8123-bab4de05fcab.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 51 52" src="https://user-images.githubusercontent.com/2189187/73733610-2f8f1880-4734-11ea-8a6f-24901890cdae.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 51 41" src="https://user-images.githubusercontent.com/2189187/73733611-3027af00-4734-11ea-933e-dff489a0767d.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 51 29" src="https://user-images.githubusercontent.com/2189187/73733612-3027af00-4734-11ea-9863-5060da9f3b0a.png">
<img width="623" alt="Screenshot 2020-02-04 at 09 50 42" src="https://user-images.githubusercontent.com/2189187/73733614-3027af00-4734-11ea-9fb0-1ff8d8314a19.png">

**Comment by jeffpaul** [comment]
@pereirinha thanks for sharing these, we'll look to get them into an upcoming release.  If anyone is able to help work on a PR for these that would be greatly appreciated.  Also, if there's an ideal timeframe on when these get resolved in an upcoming release that would be great to know as well.

**Comment by brentvr** [comment]
@jeffpaul appreciate you helping to prioritise this. We're looking at a timeline of w/c 24th Feb to have this ready. Do you think that would be possible for addressing these changes and pushing a release?

**Comment by jeffpaul** [comment]
@brentvr that week seems feasible, though we'll have to shuffle some other efforts / release plans around to accommodate.  If anyone from your team is able to help pick up these into a PR then that would expedite things, otherwise I'll look to see who on our team could help get this into a PR.

**Comment by asharirfan** [comment]
Hey @jeffpaul, I will be working on this issue tomorrow. I will try to send a PR ASAP.
