### ISSUE TITLE
Exclude certain post type

### ISSUE THREAD

**Issue by dzulhelmi** [10up/simple-page-ordering#47]
I have many custom post types on my website. 
How can I exclude a custom post type from using the plugin page ordering?
I want a custom post type to sort by the latest date, but others still use the plugin page ordering.

**Comment by jeffpaul** [comment]
@dzulhelmi check out the readme, it's got some details for you on the topic: https://github.com/10up/simple-page-ordering#can-i-make-my-custom-post-type-take-advantage-of-this-plug-in

**Comment by dinhtungdu** [comment]
This question was answered on w.org too: https://wordpress.org/support/topic/exclude-certain-custom-post-type/#post-12585000

**Comment by dzulhelmi** [comment]
> @dzulhelmi check out the readme, it's got some details for you on the topic: https://github.com/10up/simple-page-ordering#can-i-make-my-custom-post-type-take-advantage-of-this-plug-in

I don't understand how to use that

**Comment by dzulhelmi** [comment]
> This question was answered on w.org: https://wordpress.org/support/topic/exclude-certain-custom-post-type/#post-12585000

Thanks, I have close the thread and mark as resolved.
