### ISSUE TITLE
Ability to order sticky posts

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-page-ordering#48]
**Is your enhancement related to a problem? Please describe.**
As [previously requested on WordPress.ORG](https://wordpress.org/support/topic/feature-request-ordering-sticky-posts/):
>Is it possible to extend you plugin functionalities to include ordering sticky posts, it would be great to have such a capability in the next releases of your nice plugin.

**Describe the solution you'd like**

On top of being able to order normal posts, we'd include the ability to order "sticky" posts.  Presumably all "sticky" posts would be ordered amongst themselves and appear first, then followed by whatever order the normal posts have been ordered into.

**Designs**

n/a

**Describe alternatives you've considered**

none

**Additional context**

none

**Comment by abazeed** [comment]
That will be great, many thanks @jeffpaul .

**Comment by oscarssanchez** [comment]
Hi @jeffpaul , @abazeed 

If I'm not mistaken, simple page ordering only works with `pages` and hierarchical post types. I just tested this and looks like the plugin indeed doesn't work on `posts`. 

It also looks like post types other than `post` do not have core compatibility with sticky posts per https://core.trac.wordpress.org/ticket/12702 so this is a little confusing to me.

I was looking into something to work for fun so just wanted to double check with you I got the issue right?

**Comment by jeffpaul** [comment]
@oscarssanchez sounds like that's all correct, which if I'm understanding means this isn't something that can be addressed without resolving the underlying core issue... correct?

**Comment by oscarssanchez** [comment]
I think so yes @jeffpaul !

Would be great if someone else from open source can give their input to confirm as well!

**Comment by dinhtungdu** [comment]
@jeffpaul @oscarssanchez Even we can make the `post` sortable, sticky posts won't follow `menu_order` in query, see [here](https://github.com/WordPress/wordpress-develop/blob/f5dde31290667669e4625a86d163cc8c2e76912d/src/wp-includes/class-wp-query.php#L3129-L3171).

So I suggest that we close this issue with a `wontfix` label.

**Comment by jeffpaul** [comment]
Per research and confirmation, closing this as `wontfix` at least until core supports sticky posts being sortable/orderable.
