### ISSUE TITLE
Automate the build process

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-page-ordering#57]
**Is your enhancement related to a problem? Please describe.**
Automate the build process and stop committing the built JS file.

**Describe the solution you'd like**

See above.

**Designs**

n/a

**Describe alternatives you've considered**

n/a

**Additional context**

Inherits from @helen's [comment](https://github.com/10up/simple-page-ordering/pull/53#pullrequestreview-389602202) in #53.

**Comment by oscarssanchez** [comment]
Just checking this one, it seems this is already implemented in https://github.com/10up/simple-page-ordering/commit/4f6d5c573f1df8a5c65769e94d46246f1e21a918 @jeffpaul
