### ISSUE TITLE
Reordering posts doesn't work (sometime)

### ISSUE THREAD

**Issue by dinhtungdu** [10up/simple-page-ordering#61]
**Describe the bug**
From wordpress.org support forum:

> There is one small bug that I notice sometimes, and i’l try to explain it clearly. When I drag/drop a post to another sort order position (if the difference in sort orders is large) it doesn’t move all the way. If i refresh the window its a couple positions off. I then need to move the other surrounding posts via drag/drop to get the exact order i want. It take a little (1) drag/drop, then (2) refresh page, then (3) see if everything is in the correct place, then (4) drag/drop other posts to get the proper order.

Original report: https://wordpress.org/support/topic/simple-page-ordering-fails-to-save-new-order-spins-forever/page/2/#post-12940827

**Comment by dinhtungdu** [comment]
@jeffpaul Currently, I can't reproduce this problem, so I think we should punt this to future release and come back to this when we can reproduce the issue.

**Comment by jeffpaul** [comment]
Closing as not reproducible.
