### ISSUE TITLE
Test against WordPress 5.7

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-page-ordering#65]
**Is your enhancement related to a problem? Please describe.**
Once WordPress 5.7 is released, we'll want to test Simple Page Ordering to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [x] test Simple Page Ordering on WordPress 5.7
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [x] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
Related: https://github.com/10up/simple-page-ordering/issues/46.

**Comment by jeffpaul** [comment]
@robwent thanks for the help testing this, its greatly appreciated!  For the non-hierarchical CPT that you created, did you enable support for ordering as described at https://github.com/10up/simple-page-ordering#can-i-make-my-custom-post-type-take-advantage-of-this-plug-in?  If so, which method?

**Comment by robwent** [comment]
I added the 'page attributes' option to the post type.

To be honest, I missed the part about the sort by order link (I only tested after seeing this issue). I see the link now and it works.

Is there any reason why the standard behaviour can't be enabled when the page attributes supports option is enabled?

**Comment by ankitguptaindia** [comment]
@jeffpaul 

Tested plugin Simple Page Ordering with Latest WordPress 5.7.1. Working expected and couldn't find any trouble using reordering features.

 -  Tested with Pages
 - By creating new Custom Post Types
 - Tested on Latest Chrome, Firefox, Safari, Edge and IE-11
 

**Final Summary -**  we can update readme and release for **Tested up to WordPress 5.7.1**
