### ISSUE TITLE
Setup Cypress for E2E testings

### ISSUE THREAD

**Issue by dinhtungdu** [10up/simple-page-ordering#77]
### Is your enhancement related to a problem? Please describe.

As we're switching to use Cypress for E2E testings, and ultimately replace WP Acceptance, it's great to start implementing Cypress E2E testings for this plugin.

Some of 10up open-source plugins using Cypress:
- https://github.com/10up/restricted-site-access
- https://github.com/10up/simple-podcasting

Other useful links:
- 10up Open Source Best Practices for Testing: https://10up.github.io/Open-Source-Best-Practices/testing/
- https://github.com/10up/cypress-wp-setup/ && https://github.com/10up/cypress-wp-utils will be helpful in getting this spun up and some initial test commands to leverage.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Let's make sure to remove WP Acceptance as part of the work to add Cypress to this repo.
