### ISSUE TITLE
`PLUGIN_VERSION` is too generic

### ISSUE THREAD

**Issue by dinhtungdu** [10up/simple-page-ordering#78]
### Is your enhancement related to a problem? Please describe.

In https://github.com/10up/simple-page-ordering/pull/74, we introduced a new constant named `PLUGIN_VERSION`. IMO that constant is too generic and has a higher chance to be conflicted with other plugins/themes. I think we should change it to one that is specific to Simple Page Ordering.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Totally agree, nice catch.  `SIMPLE_PAGE_ORDERING_VERSION` might be better.
