### ISSUE TITLE
Endpoints in REST not translateable

### ISSUE THREAD

**Issue by kebbet** [10up/simple-page-ordering#91]
### Is your enhancement related to a problem? Please describe.

REST endpoint descriptions can not be translated. Maybe a deliberate choice, but translating them wont not hurt anyone?

https://github.com/10up/simple-page-ordering/blob/develop/simple-page-ordering.php#L414-L453

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@kebbet welcome to Simple Page Ordering and thanks for the callout (was not intentional) and resulting PR!  We'll get that through review and let you know of any questions or concerns then... thanks!
